services:
  postgres:
    image: postgres:16
    container_name: startsi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: startsi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - startsi-postgres:/var/lib/postgresql/data
volumes:
  startsi-postgres:
